### ISSUE TITLE
turf.inside giving false positive

### ISSUE THREAD

**Issue by kujosHeist** [Turfjs/turf-inside#15]
The linked gist shows a polygon and a point outside of it.

But turf.inside returns true when called with the point and polygon

gist:
http://geojson.io/#id=gist:kujosHeist/1030e392bd751daf5d9af57aa412a49c&map=3/46.80/-22.76

sample code:

```javascript
var turf = require('turf')

var pt1 = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Point",
    "coordinates": [
      -9.9964077,
      53.8040989
    ]
  }
};

var poly = 	   {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [5.080336744095521,67.89398938540765],
        [0.35070899909145403,69.32470003971179],
        [-24.453622256504122,41.146696777884564],
        [-21.6445524714804,40.43225902006474],
        [5.080336744095521,67.89398938540765]
      ]
    ]
  }
};

var result = turf.inside(pt1, poly);
console.log(result);
```

**Comment by DenisCarriere** [comment]
The map you are seeing the point is actually misrepresenting the point since it uses World Web Mercator projection (EPSG:3857), the point is actually inside and the result (`true`) is correct.

![image](https://cloud.githubusercontent.com/assets/550895/26831735/3bd7d3fe-4a9b-11e7-9cda-1e363da4bc22.png)
viewing same point/polygon using WGS84 with QGIS

**Comment by kujosHeist** [comment]
Thanks for explaining that! Do you know how to change the projection in geojson.io or better yet, cesium.js, to display the point inside the polygon? 

I've also asked the question over on stackoverflow:

https://stackoverflow.com/questions/44394090/change-map-projection-in-cesium-js-to-match-results-from-turf-js-inside-query

**Comment by DenisCarriere** [comment]
No easy solution for that, however I thought cesium was using a Globe projection, you are still getting that same issue with cesium?

**Comment by kujosHeist** [comment]
Yeah I'm having the same issue with Cesium, it seems to be using them same projection as geojson.io, because the points and polygons match up perfectly, here's a screenshot of another example:

![overpass-outside](https://user-images.githubusercontent.com/5103738/26874101-4007347c-4b74-11e7-8ad0-8fd6c942e863.PNG)

**Comment by DenisCarriere** [comment]
Yea that's just because the polygon geometry is so big and the projection is misrepresenting it when in reality the point is inside that polygon.

No good solution for this.

**Comment by kujosHeist** [comment]
Yeah I was thinking that, thanks for all your help!
