### ISSUE TITLE
support raw geometries

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-inside#5]

**Comment by tchannel** [comment]
I'm working on [turfjs/turf-to-geometries](https://github.com/turfjs/turf-to-geometries) (and [turfjs/turf-to-features](https://github.com/turfjs/turf-to-features)), which aims to stop us from replicating logic to ensure input geojson is geometries / features. Once it's published, you could do something like: 

```javascript
toGeometries = require('turf-to-geometries')

// ...

module.exports = function(point, polygon) {
  invariant.featureOf(point, 'Point', 'inside');
  var polys = toGeometry(polygon).coordinates;
  var pt = toGeometry(point).coordinates.slice();
```

This means the user could pass either Features or Geometries, and we'll properly extract the geometry in either case.

**Comment by morganherlocker** [comment]
Nope, just going with features

**Comment by tchannel** [comment]
![](http://31.media.tumblr.com/62ff8d256e0b84273ec621b07dea4bfa/tumblr_n32wezVes41tw1vhco1_500.gif)
